### ISSUE TITLE
[Bug] Failed to upload resource to cfx portal

### ISSUE THREAD

**Issue by HeyyCzer** [Tynopia/cfx-portal-upload#34]
Error when upload files to portal

```yml
name: Upload package

on: ["push", "workflow_dispatch"]

jobs:
  upload:
    name: Upload to Portal
    runs-on: ubuntu-latest
    steps:
      - name: Upload Escrow Resource
        uses: Tynopia/cfx-portal-upload@v1.2.2
        with:
          cookie: ${{ secrets.FORUM_COOKIE }}
          assetId: xxx
          assetName: "heyy_protections"
          makeZip: true
```

## Errors
Using keymaster to find the reason of the failure
* `no resources found`

## Screenshots
![Image](https://github.com/user-attachments/assets/f8bb46ce-8273-47af-9606-29836c14abb8)
![Image](https://github.com/user-attachments/assets/47ed108a-af53-4d4f-ad07-0c6af5072360)
